# Generated by Django 4.0 on 2022-01-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='visitation',
            new_name='city',
        ),
    ]
